---
name: 'HA Matter Bridge'
version: '0.6.4'
slug: ha-matter-bridge
description: This project serves as a proof of concept to connect HomeAssistant devices to Voice Assistants through the Matter Protocol.
init: false
arch:
    - amd64
ports:
    5540/tcp: 5540

host_network: true
hassio_role: homeassistant
hassio_api: true
homeassistant_api: true
auth_api: true
map:
    - addon_config:rw
image: ghcr.io/jatus93/ha-matter-bridge
