---
name: 'HA Matter Bridge'
version: '0.7.3'
slug: ha-matter-bridge
description: This project serves as a proof of concept to connect HomeAssistant devices to Voice Assistants through the Matter Protocol.
init: false
arch:
    - amd64
ports:
    5540/tcp: 5540
    2839/tcp: 2839

host_network: true
hassio_role: homeassistant
hassio_api: true
homeassistant_api: true
auth_api: true
map:
    - addon_config:rw

webui: http://[HOST]:[PORT:2839]/
image: ghcr.io/jatus93/ha-matter-bridge
