name: Release-main
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Path echo
        run: |
          ls -al
          cd matter-bridge && ls -al
          echo ${{ github.actor }}

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: cd matter-bridge && yarn --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: cd matter-bridge && npx semantic-release
      - name: Run read-yaml action
        id: yaml-data
        uses: jbutcher5/read-yaml@1.6
        with:
          file: "./matter-bridge/config.yml"
          key-path: '["version"]'

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"

      - name: Log in to the Container registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.yaml-data.outputs.data }}
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ./matter-bridge
          file: ./matter-bridge/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: git push
        env:
          HUSKY: 0
        run: |
          git config --local user.email "github-action[bot]@users.noreply.github.com"
          git config --local user.name "CI [BOT]"
          git add matter-bridge/config.yml
          git commit -m "chore(config.yml): bump version to ${{steps.yaml-data.outputs.data}} [ci skip]"
          git push
